# Generated by Django 3.1.7 on 2021-03-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=models.JSONField(null=True),
        ),
    ]
